Implemented mark stock item as used
mzuri-tech/InventoryService pull request #25
Opened 2021-03-18 13:26 UTC by sapphire1996

This PR adds quantity property to stockitemCategoty entity, adds migration, and implemented mark stock item as used

2021-03-18 14:25 UTC, eskye submitted a review, later dismissed

2021-03-18 14:29 UTC, eskye approved these changes

2021-03-18 15:40 UTC, henryezeanya requested changes

2021-03-18 15:40 UTC, henryezeanya commented on src/InventoryService.Application/Services/Implementations/StockItemService.cs
> +                    throw new UserFriendlyException((int)ErrorCodes.DataNotFound, AppErrorMessages.AvailableQuantityIsLower);
Use an appropriate error code here, the error code DataNotFound doesn't sound appropriate because this is not the case of a missing record.  Use InvalidRequest instead

2021-03-19 11:07 UTC, henryezeanya approved these changes

2021-03-19 11:16 UTC, eskye approved these changes

2021-03-19 11:16 UTC, merged